version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
