# Generated by Django 4.2.5 on 2023-10-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.spreadsheet')),
            ],
            options={
                'unique_together': {('spreadsheet', 'cell_id')},
            },
        ),
    ]
