# Generated by Django 4.2.5 on 2023-10-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='datastore',
        ),
    ]
